version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_USER: tina
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"  # مستقیماً پورت را بنویسید ساده‌تر است
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tina"]  # اصلاح شده
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: